name: LyricWiki Gracenote

variables:
    artist:
        type: artist
        filters:
        - [regex, "\\s+", _]
        - urlencode
    title:
        type: title
        filters: artist 

post-filters:
- br2nl
- p2break
- strip_html
- entity_decode
- utf8_encode
- trim

config:
    url: "http://lyrics.wikia.com/Gracenote:{artist}:{title}"
    pattern: "'lyricbox'>.*?/></a></div>(?<lyrics>.*?)<!--"
