name: MetroLyrics

variables:
    artist:
        type: artist
        filters:
        - diacritics2ascii
        - lowercase
        - [regex, '[^\sa-z0-9]\s*', ""]
        - [strip_nonascii, -]
    title:
        type: title
        filters: artist

config:
    url: "http://www.metrolyrics.com/{title}-lyrics-{artist}.html"
    pattern: ['<div id="lyrics-body">(?<lyrics>.*?)</div>', s]
    
post-filters:
- br2nl
- strip_html
- strip_links
- entity_decode
- clean_spaces
- utf8_encode

validations:
- [not contains, Click here to submit these lyrics]