name: Oldies Lyrics

variables:
    artist:
        type: artist
        filters:
        - diacritics2ascii
        - lowercase
        - [regex, '[^\sa-z0-9]\s*', ""]
        - [strip_nonascii, _]
    title:
        type: title
        filters: artist

config:
    url: "http://oldielyrics.com/lyrics/{artist}/{title}.html"
    pattern: ['<div\s+class="lyrics"[^>]*>\s*<p>(?<lyrics>.+)</p>\s*</div>', s]
    
post-filters:
- br2nl
- p2break
- strip_html
- strip_links
- entity_decode
- clean_spaces
- utf8_encode