name: "pinkradio.com"

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - [strip_nonascii, -]
    title:
        type: title
        filters: artist

config:
    url: "http://pinkradio.com/naslov/{title}"
    pattern: ['<span class="Stil9">\\s*(?<lyrics>.*?)</span>', s]
    
post-filters:
- strip_html
- entity_decode
- br2nl