name: Rap Genius

variables:
    artist:
        type: artist
        filters:
        - diacritics2ascii
        - lowercase
        - [regex, '[^\sa-z0-9]\s*', ""]
        - [strip_nonascii, -]
    title:
        type: title
        filters: artist

config:
    url: "http://rapgenius.com/{artist}-{title}-lyrics"
    pattern: ['<div\s+class="lyrics"[^>]*?>(?<lyrics>.*?)</div>', s]
    
post-filters:
- strip_html
- clean_spaces
- utf8_encode