name: "teksty.org"

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - [strip_nonascii, -]
    title:
        type: title
        filters: artist

config:
    url: "http://teksty.org/{artist},{title},tekst-piosenki"
    pattern: ['<div\\s+class="songText"[^>]*>(?<lyrics>.*?)</div>', s]
    
post-filters:
- strip_html
- clean_spaces
- utf8_encode